name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
            - nombre: Primera interacción
  usos: acciones/primera-interacción@v1.3.0
  con:
    Token para el repositorio. Se puede pasar usando {{ secrets.GITHUB_TOKEN }}
    token de repositorio:
    # Comentario para publicar sobre el primer problema de un individuo
    mensaje de problema: # opcional
    # Comentario para publicar en la primera solicitud de extracción de un individuo
    pr-message: # opcional
          
