name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
            - nombre: Primera interacción
  usos: acciones/primera-interacción@v1.3.0
  con:
    Token para el repositorio. Se puede pasar usando {{ secrets.GITHUB_TOKEN }}
    token de repositorio:
    # Comentario para publicar sobre el primer problema de un individuo
    mensaje de problema: # opcional
    # Comentario para publicar en la primera solicitud de extracción de un individuo
    pr-message: # opcional
          
            - nombre: Configurar el entorno Node.js
  usos: acciones/setup-node@v4.2.0
  con:
    # Establezca always-auth en npmrc.
    always-auth: # opcional, el valor predeterminado es falso
    Especificación de la versión a utilizar. Ejemplos: 12.x, 10.15.1, >=10.15.0.
    node-version: # opcional
    Archivo que contiene la especificación de la versión a utilizar. Ejemplos: package.json, .nvmrc, .node-version, .tool-versions.
    archivo-versión-nodo: # opcional
    # Arquitectura de destino que usará Node. Ejemplos: x86, x64. Se usará la arquitectura del sistema por defecto.
    arquitectura: # opcional
    # Configure esta opción si desea que la acción busque la última versión disponible que satisfaga la especificación de la versión.
    check-latest: # opcional
    Registro opcional para la autenticación. Se establecerá el registro en archivos .npmrc y .yarnrc a nivel de proyecto y se configurará la autenticación para leer desde env.NODE_AUTH_TOKEN.
    URL del registro: # opcional
    # Ámbito opcional para la autenticación en registros con ámbito. Se recurrirá al propietario del repositorio al usar el registro de paquetes de GitHub (https://npm.pkg.github.com/).
    alcance: # opcional
    # Se usa para extraer distribuciones de nodos de node-versions. Dado que hay un valor predeterminado, normalmente no lo proporciona el usuario. Al ejecutar esta acción en github.com, el valor predeterminado es suficiente. Al ejecutar en GHES, puede pasar un token de acceso personal a github.com si experimenta limitaciones de velocidad.
    token: # opcional, el valor predeterminado es ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Se utiliza para especificar un gestor de paquetes para el almacenamiento en caché en el directorio predeterminado. Valores admitidos: npm, yarn, pnpm.
    caché: # opcional
    # Se utiliza para especificar la ruta a un archivo de dependencia: package-lock.json, yarn.lock, etc. Admite caracteres comodín o una lista de nombres de archivos para almacenar en caché múltiples dependencias.
    ruta de dependencia de caché: # opcional
      
            - nombre: Configurar el entorno Node.js
  usos: acciones/setup-node@v4.2.0
  con:
    # Establezca always-auth en npmrc.
    always-auth: # opcional, el valor predeterminado es falso
    Especificación de la versión a utilizar. Ejemplos: 12.x, 10.15.1, >=10.15.0.
    node-version: # opcional
    Archivo que contiene la especificación de la versión a utilizar. Ejemplos: package.json, .nvmrc, .node-version, .tool-versions.
    archivo-versión-nodo: # opcional
    # Arquitectura de destino que usará Node. Ejemplos: x86, x64. Se usará la arquitectura del sistema por defecto.
    arquitectura: # opcional
    # Configure esta opción si desea que la acción busque la última versión disponible que satisfaga la especificación de la versión.
    check-latest: # opcional
    Registro opcional para la autenticación. Se establecerá el registro en archivos .npmrc y .yarnrc a nivel de proyecto y se configurará la autenticación para leer desde env.NODE_AUTH_TOKEN.
    URL del registro: # opcional
    # Ámbito opcional para la autenticación en registros con ámbito. Se recurrirá al propietario del repositorio al usar el registro de paquetes de GitHub (https://npm.pkg.github.com/).
    alcance: # opcional
    # Se usa para extraer distribuciones de nodos de node-versions. Dado que hay un valor predeterminado, normalmente no lo proporciona el usuario. Al ejecutar esta acción en github.com, el valor predeterminado es suficiente. Al ejecutar en GHES, puede pasar un token de acceso personal a github.com si experimenta limitaciones de velocidad.
    token: # opcional, el valor predeterminado es ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Se utiliza para especificar un gestor de paquetes para el almacenamiento en caché en el directorio predeterminado. Valores admitidos: npm, yarn, pnpm.
    caché: # opcional
    # Se utiliza para especificar la ruta a un archivo de dependencia: package-lock.json, yarn.lock, etc. Admite caracteres comodín o una lista de nombres de archivos para almacenar en caché múltiples dependencias.
    ruta de dependencia de caché: # opcional

                      - nombre: Cerrar problemas obsoletos
  usos: acciones/stale@v9.1.0
  con:
    Token para el repositorio. Se puede pasar mediante `{{ secrets.GITHUB_TOKEN }}`.
    repo-token: # opcional, el valor predeterminado es ${{ github.token }}
    # El mensaje que se publicará sobre el problema al etiquetarlo. Si no se proporciona ninguno, no se marcarán los problemas como obsoletos.
    mensaje de problema obsoleto: # opcional
    # El mensaje que se publicará en la solicitud de extracción al etiquetarla. Si no se proporciona ninguno, no se marcarán las solicitudes de extracción como obsoletas.
    mensaje-previo-obsoleto: # opcional
    # El mensaje que se publicará en el problema al cerrarlo. Si no se proporciona ninguno, no se comentará al cerrar un problema.
    mensaje de cierre de problema: # opcional
    # El mensaje que se publicará en la solicitud de extracción al cerrarla. Si no se proporciona ninguno, no se comentará al cerrar una solicitud de extracción.
    cerrar-pr-mensaje: # opcional
    # El número de días que puede tener una incidencia o solicitud de extracción antes de que se marque como obsoleta. Establézcalo en -1 para que nunca se marquen incidencias ni solicitudes de extracción como obsoletas automáticamente.
    días antes de que se vuelva obsoleto: # opcional, el valor predeterminado es 60
    # El número de días que puede tener un problema antes de que se marque como obsoleto. Configure en -1 para que nunca se marquen los problemas como obsoletos automáticamente. Anule la opción "días antes de que se marque como obsoleto" solo para los problemas.
    días antes de la emisión obsoletos: # opcional
    # El número de días que una solicitud de extracción puede tener antes de que se marque como obsoleta. Se establece en -1 para que nunca se marquen las solicitudes de extracción como obsoletas automáticamente. Anula la opción "días antes de que se marquen obsoletas" solo para las solicitudes de extracción.
    días-antes-de-pr-stale: # opcional
    El número de días que se debe esperar para cerrar una incidencia o solicitud de extracción después de que se marque como obsoleta. Se establece en -1 para no cerrar nunca incidencias ni solicitudes de extracción obsoletas.
    días-antes-del-cierre: # opcional, el valor predeterminado es 7
    El número de días que se debe esperar para cerrar un problema después de que se marque como obsoleto. Se establece en -1 para no cerrar nunca los problemas obsoletos. Anula la opción "días antes del cierre" solo para los problemas.
    días antes del cierre de la emisión: # opcional
    # El número de días que se debe esperar para cerrar una solicitud de extracción después de que se marque como obsoleta. Se establece en -1 para no cerrar nunca las solicitudes de extracción obsoletas. Se anula la opción "días antes del cierre" solo para las solicitudes de extracción.
    días antes del cierre: # opcional
    # La etiqueta que se aplicará cuando un problema esté obsoleto.
    stale-issue-label: # opcional, el valor predeterminado es Obsoleto
    # La etiqueta que se aplicará cuando se cierre un problema.
    cerrar-etiqueta-de-problema: # opcional
    # Las etiquetas que indican que un problema no se marca como obsoleto. Separe las etiquetas con comas (p. ej., "etiqueta1,etiqueta2").
    etiquetas-de-emisión-exentas: # opcional, el valor predeterminado es
    # El motivo a utilizar al cerrar un problema.
    close-issue-reason: # opcional, el valor predeterminado es not_planned
    # La etiqueta que se aplicará cuando una solicitud de extracción esté obsoleta.
    stale-pr-label: # opcional, el valor predeterminado es obsoleto
    # La etiqueta que se aplicará cuando se cierre una solicitud de extracción.
    close-pr-label: # opcional
    # Las etiquetas que indican que una solicitud de extracción está exenta de marcarse como obsoleta. Separe las etiquetas con comas (p. ej., "etiqueta1,etiqueta2").
    except-pr-labels: # opcional, el valor predeterminado es
    Los hitos que indican que una incidencia o una solicitud de incorporación de cambios no se marcan como obsoletos. Separe los hitos con comas (p. ej., "hito1,hito2").
    exentos-hitos: # opcional, el valor predeterminado es
    # Los hitos que eximen a un problema de marcarse como obsoleto. Separe los hitos con comas (p. ej., "hito1,hito2"). Anule la opción "hitos exentos" solo para los problemas.
    eximir-emisión-hitos: # opcional, el valor predeterminado es
    # Los hitos que eximen a una solicitud de incorporación de cambios de marca como obsoleta. Separe los hitos con comas (p. ej., "hito1,hito2"). Anule la opción "exempt-milestones" solo para las solicitudes de incorporación de cambios.
    except-pr-milestones: # opcional, el valor predeterminado es
    # Exime todos los problemas y solicitudes de extracción con hitos de marcarse como obsoletos. El valor predeterminado es falso.
    except-all-milestones: # opcional, el valor predeterminado es falso
    # Excluir todos los problemas con hitos de la lista de obsoletos. Anular la opción "excluir todos los hitos" solo para los problemas.
    except-all-issue-milestones: # opcional, el valor predeterminado es
    # Eximir a todas las solicitudes de extracción con hitos de marcarse como obsoletas. Anular la opción "exempt-all-milestones" solo para las solicitudes de extracción.
    except-all-pr-milestones: # opcional, el valor predeterminado es
    # Solo se verifican los problemas o solicitudes de extracción con todas estas etiquetas si están obsoletos. El valor predeterminado es `` (deshabilitado) y puede ser una lista de etiquetas separadas por comas.
    only-labels: # opcional, el valor predeterminado es
    # Solo se verifican los problemas o solicitudes de extracción con al menos una de estas etiquetas si están obsoletos. El valor predeterminado es `` (deshabilitado) y puede ser una lista de etiquetas separadas por comas.
    any-of-labels: # opcional, el valor predeterminado es
    # Solo se verifican los problemas con al menos una de estas etiquetas si están obsoletos. El valor predeterminado es `` (deshabilitado) y puede ser una lista de etiquetas separadas por comas. Anule la opción "cualquiera de las etiquetas" solo para los problemas.
    any-of-issue-labels: # opcional, el valor predeterminado es
    # Solo se verifican las solicitudes de extracción con al menos una de estas etiquetas si están obsoletas. El valor predeterminado es `` (deshabilitado) y puede ser una lista de etiquetas separadas por comas. Anule la opción "cualquiera de las etiquetas" solo para las solicitudes de extracción.
    any-of-pr-labels: # opcional, el valor predeterminado es
    # Solo se verifican los problemas con todas estas etiquetas si están obsoletos. El valor predeterminado es `[]` (deshabilitado) y puede ser una lista de etiquetas separadas por comas. Anule la opción "only-labels" solo para los problemas.
    only-issue-labels: # opcional, el valor predeterminado es
    # Solo se verifican las solicitudes de extracción con todas estas etiquetas si están obsoletas. El valor predeterminado es `[]` (deshabilitado) y puede ser una lista de etiquetas separadas por comas. Anule la opción "only-labels" solo para las solicitudes de extracción.
    only-pr-labels: # opcional, el valor predeterminado es
    # El número máximo de operaciones por ejecución, utilizado para controlar la limitación de velocidad (CRUD de API de GitHub relacionado).
    operaciones-por-ejecución: # opcional, el valor predeterminado es 30
    # Eliminar etiquetas obsoletas de problemas y solicitudes de extracción cuando se actualizan o se comentan.
    remove-stale-when-updated: # opcional, el valor predeterminado es verdadero
    # Eliminar las etiquetas obsoletas de los problemas al actualizarse o comentarse. Anular la opción "eliminar obsoleto al actualizarse" solo para los problemas.
    remove-issue-stale-when-updated: # opcional, el valor predeterminado es
    # Eliminar las etiquetas obsoletas de las solicitudes de extracción cuando se actualicen o se comenten. Anular la opción "eliminar-obsoletas-al-actualizar" solo con respecto a las solicitudes de extracción.
    remove-pr-stale-when-updated: # opcional, el valor predeterminado es
    # Ejecute el procesador en modo de depuración sin realizar ninguna operación en problemas en vivo.
    solo depuración: # opcional, el valor predeterminado es falso
    # El orden para obtener problemas o solicitudes de extracción. El valor predeterminado es "falso" (orden descendente).
    ascendente: # opcional, el valor predeterminado es falso
    # Eliminar la rama git después de cerrar una solicitud de extracción obsoleta.
    delete-branch: # opcional, el valor predeterminado es falso
    # La fecha utilizada para omitir la acción obsoleta en el problema o solicitud de extracción creada antes de ella (ISO 8601 o RFC 2822).
    fecha de inicio: # opcional, el valor predeterminado es
    # Los usuarios asignados que eximen una incidencia o solicitud de extracción de marcarse como obsoleta. Separe los usuarios asignados con comas (p. ej., "usuario1,usuario2").
    cesionarios exentos: # opcional, el valor predeterminado es
    # Los asignados que eximen un problema de marcarse como obsoleto. Separe los asignados con comas (p. ej., "usuario1,usuario2"). Anule la opción "eximir-asignados" solo para los problemas.
    exentos-emisión-asignados: # opcional, el valor predeterminado es
    # Los usuarios asignados que eximen una solicitud de extracción de ser marcada como obsoleta. Separe los usuarios asignados con comas (p. ej., "usuario1,usuario2"). Anule la opción "eximir-asignados" solo para las solicitudes de extracción.
    eximir-pr-asignados: # opcional, el valor predeterminado es
    # Exime a todos los problemas y solicitudes de extracción con asignaciones de marcarse como obsoletos. El valor predeterminado es "falso".
    eximir a todos los asignados: # opcional, el valor predeterminado es falso
    # Eximir a todos los problemas con asignatarios de marcarse como obsoletos. Anular la opción "eximir a todos los asignados" solo para los problemas.
    eximir a todos los asignados: # opcional, el valor predeterminado es
    # Eximir a todas las solicitudes de extracción con asignaciones de ser marcadas como obsoletas. Anular la opción "exempt-all-assignes" solo para las solicitudes de extracción.
    eximir a todos los asignatarios de pr: # opcional, el valor predeterminado es
    # Exime a los borradores de solicitudes de extracción de marcarse como obsoletos. El valor predeterminado es falso.
    eximir-borrador-pr: # opcional, el valor predeterminado es falso
    # Mostrar algunas estadísticas al final sobre el flujo de trabajo obsoleto (solo cuando los registros están habilitados).
    enable-statistics: # opcional, el valor predeterminado es verdadero
    # Una lista delimitada por comas de etiquetas para agregar cuando un problema o una solicitud de extracción deja de estar obsoleto.
    etiquetas-para-agregar-cuando-no-estén-obsoletas: # opcional, el valor predeterminado es
    # Una lista delimitada por comas de etiquetas para eliminar cuando un problema o una solicitud de extracción se vuelve obsoleto.
    etiquetas-para-eliminar-cuando-estén-obsoletas: # opcional, el valor predeterminado es
    # Una lista delimitada por comas de etiquetas para eliminar cuando un problema o una solicitud de extracción deja de estar obsoleto.
    etiquetas-para-eliminar-cuando-no-estén-obsoletas: # opcional, el valor predeterminado es
    # Cualquier actualización (actualización/comentario) puede restablecer el tiempo de inactividad obsoleto en los problemas y solicitudes de extracción.
    ignore-updates: # opcional, el valor predeterminado es falso
    Cualquier actualización (actualización/comentario) puede restablecer el tiempo de inactividad de los problemas. Anule la opción "ignorar actualizaciones" solo para los problemas.
    ignore-issue-updates: # opcional, el valor predeterminado es
    Cualquier actualización (actualización/comentario) puede restablecer el tiempo de inactividad de las solicitudes de extracción. Anule la opción "ignorar actualizaciones" solo para las solicitudes de extracción.
    ignore-pr-updates: # opcional, el valor predeterminado es
    # Sólo los problemas o las solicitudes de extracción con un cesionario se marcarán como obsoletos automáticamente.
    include-only-assigned: # opcional, el valor predeterminado es falso
          
